### ISSUE TITLE
Please add --paper-toggle-button-error-color that gets applied when element is invalid, like --paper-checkbox-error-color

### ISSUE THREAD

**Issue by mercmobily** [PolymerElements/paper-toggle-button#100]
At the moment, it doesn't seem to be possible to change the colour of this element in case it's `invalid`. I realise that it's not common for `true` or `false` to be invalid as such, but there are indeed cases (see: it needs to be true when you press "I accept" on a  screen with ToS).

**Comment by notwaldorf** [comment]
Here's a JSBin styling it when it's invalid: http://jsbin.com/fojefel/edit?html,output.

Is this issue that it isn't styled automatically (like paper-checkbox is), or that it isn't stylable at all?

**Comment by mercmobily** [comment]
Monica, please forgive my clumsiness. I am supposed to make your life easier, and I am obviously failing at that.
I updated the title, and yes, that's exactly what I meant: the element implements `Polymer.IronValidatableBehavior` (through  `Polymer.PaperCheckedElementBehavior`). So, ideally it should theme itself accordingly when it's "invalid", like most other widgets do.

Sorry about being so confusing, and thank you for redirecting me...

**Comment by notwaldorf** [comment]
No worries! I was just making sure I wasn't going to do extra work unless someone actually needed it 😂  

/cc @bicknellr who owns this element. I can send a PR for this if you want

**Comment by mercmobily** [comment]
Wow... thank you! I always learn something when I see these PRs. I didn't know you could do:

```
  :host([invalid]) .toggle-bar {
     background-color: var(--paper-toggle-button-invalid-bar-color, --error-color);
   }
```

That is, have a selector _following_ the :host one. That's really nice and handy to know!

Thanks a lot...
