### ISSUE TITLE
"Read only" mode? 

### ISSUE THREAD

**Issue by guss77** [PolymerElements/paper-toggle-button#126]
### Description

I want to be able to use the paper-toggle-button to show the status of an item (which could be active or inactive) but without the user being able to change it.

To prevent modifications I've set the element's `disabled` attribute but that changes the color of the bar and button so it no longer looks to be "on". From looking at the code, unlike all the other modes, there doesn't seem to be a CSS option to change the "disabled" color.

### Expected outcome

Ideally it would be possible to put the toggle button into a "read-only mode" where it rejects attempts to modify it. Less ideally we would be able to set the color for "on but disabled" and "off but disabled" using CSS

### Actual outcome

"disabled mode" always looks the same without the ability to customize.

**Comment by divanvisagie** [comment]
I actually forked this for a work project to get this working, It didn't require too much modification.
All that I did was enable the user to set the disabled colors. Will do a public fork and let's see if we can a conversation going.

**Comment by divanvisagie** [comment]
@guss77 , [this](https://github.com/divanvisagie/paper-toggle-button/commit/0834472f121abeb4562ddc2140b0e0490553bbd6) is what I have, the effect is the following.

<img width="517" alt="screen shot 2017-12-05 at 13 20 32" src="https://user-images.githubusercontent.com/2023086/33604683-8cd3e9a6-d9bf-11e7-8254-c2ab9d107301.png">

**Comment by guss77** [comment]
Thanks @divanvisagie ! Unfortunately this solution is not ideal for me because I'd need to mimic the default toggle button style in custom CSS, and if the default ever changes (or is changed globally) I have to remember to go back into the relevant module and change it as well.

But after reviewing your change, I was inspired to do the implementation of the `readonly` feature myself, and its available as PR #130 .

That PR is basically just preventing manipulation of the `active` state of the toggle, which preserves all the styling and behavior of a standard toggle button, including the ripple effects when clicked - so the control responds and doesn't look like its stuck, it just refuses to be edited.

**Comment by grudra7714** [comment]
You can also  add ```pointer-events: none``` style to your paper-toggle-button
![peek 2018-03-07 11-41](https://user-images.githubusercontent.com/12394597/37105269-aaebc410-21fc-11e8-9599-024a1cd66c2d.gif)

**Comment by notwaldorf** [comment]
In general, having the UI imply it accepts changes but then silently rejecting them is infuriating for a user. In the gif above, the button looks clickable, and you click it, and nothing happens, which is bad UI; if something isn’t clickable, it needs to communicate that, and this element does it by looking faded out.

I am strongly against adding such a change to this element; if you must do it locally, you can do what @gudra7714 said and add `pointer-events:none`.
