### ISSUE TITLE
The paper-styles isn't imported

### ISSUE THREAD

**Issue by manifest** [PolymerElements/paper-toggle-button#26]
The `paper-styles` are missed. If we use the only `paper-toggle-button`, without any other paper elements included, it will look quite ugly.
![paper-styles](https://cloud.githubusercontent.com/assets/439058/8634515/21f797c8-2804-11e5-8b65-94c20b657daa.png)

**Comment by notwaldorf** [comment]
This should be fixed in the latest release.
