### ISSUE TITLE
Ripple should be hidden on desktop as per spec

### ISSUE THREAD

**Issue by jscissr** [PolymerElements/paper-toggle-button#28]
The [material design spec](http://www.google.com/design/spec/components/selection-controls.html#selection-controls-switch) (bottom section) says:

> No radial reaction on desktop
#19 wants to implement a `noink` attribute to opt-out, but I think it should be disabled by default on mouse input.

**Comment by notwaldorf** [comment]
There is a `noink` attribute available now (usage: `<paper-toggle-button noink></paper-toggle-button>`). I think magically determining whether to show or hide the ripple inside the element is going to be unpredictable (there would have to be maybe a media query, and change this based on the size of the viewport, which is a bit strange). Also, for accessibility purposes, indicating what you clicked on is a Good Thing™, so I am inclined to leave it working as-is based on that argument alone :)

**Comment by jscissr** [comment]
I didn't think of media queries but detecting if it was a mouse or touch event, which should be easy. And isn't the toggling animation already enough indication? :)
