### ISSUE TITLE
Dynamically setting state on slow/polyfilled browsers locks toggle

### ISSUE THREAD

**Issue by tigerhawkvok** [PolymerElements/paper-toggle-button#29]
At all! It can't toggle "on".

Seen on MS Edge 20.10240.16384.0

**Comment by tigerhawkvok** [comment]
Traced this, and renamed the issue accordingly. **The original description is incorrect**.

It was the fact the Win beta test machine is an ancient Iconia. The actual bug is that if the state is set before the import finishes, it'll lock the state of the toggle.

Test fiddle:

http://jsfiddle.net/jhb3d2cn/5/

Since the import is handled in the body, after the call, the button is locked. However, comment the load-setting and uncomment the delayed setting and it works fine.

**Comment by notwaldorf** [comment]
@tigerhawkvok Everything works fine for me if I use `$("#loose").checked = true` instead of the `prop()` method. Is there a reason why you're not just setting the property directly?

See: http://jsfiddle.net/t7cuyk1k/

**Comment by tigerhawkvok** [comment]
@notwaldorf Really? That fiddle isn't working for me, before or after the delay. DId you mean `$("#loose").get(0).checked = true` ?

![screenshot 55](https://cloud.githubusercontent.com/assets/165937/9152252/b42c52e6-3dd5-11e5-89b4-c400f10dae2c.png)

![screenshot 57](https://cloud.githubusercontent.com/assets/165937/9152257/0525678c-3dd6-11e5-9be1-5b98dfebc0eb.png)

![screenshot 59](https://cloud.githubusercontent.com/assets/165937/9152264/3f87247e-3dd6-11e5-92a6-5eb6140e3ba6.png)

Though the delayed fiddle I sent you does:

![screenshot 56](https://cloud.githubusercontent.com/assets/165937/9152254/d7d7b8ca-3dd5-11e5-95fe-80da00cf23cc.png)

As well as directly setting it after a delay -- I see no difference

![screenshot 60](https://cloud.githubusercontent.com/assets/165937/9152265/58089fe6-3dd6-11e5-8cdf-d7c40a73465a.png)

**Comment by notwaldorf** [comment]
I still can't reproduce this. On MSEdge (20.10240.16384.0, what are these versions even) and the live demo, I tried doing `document.querySelector('paper-toggle-button').checked = true` (back and forth), and it worked fine. The jsFiddle is way out of date, so I couldn't repro it there either.
