### ISSUE TITLE
styles cannot be overriden (with mixins) unless !important (for some properties)

### ISSUE THREAD

**Issue by carolirod** [PolymerElements/paper-toggle-button#43]
here the example:
http://codepen.io/carolirod/pen/mePaeN?editors=101 

I'm using the mixins provided which should override the properties declared in the component
--paper-toggle-button-checked-bar
--paper-toggle-button-checked-button

to override border-radius declared here:
https://github.com/PolymerElements/paper-toggle-button/blob/master/paper-toggle-button.html#L105
and here:
https://github.com/PolymerElements/paper-toggle-button/blob/master/paper-toggle-button.html#L125

It could be because these ones are declared by # ids..

**Comment by carolirod** [comment]
sorry for the confusion, only the last commit should be the one (had trouble authorising the commit with the right email)

**Comment by carolirod** [comment]
sorry for the confusion... only the last commit (+PR) should be the one (had trouble authorising the commit with the right email), finally got it right...

**Comment by notwaldorf** [comment]
Fixed by #46
