### ISSUE TITLE
disabled colors incorrect

### ISSUE THREAD

**Issue by opus1269** [PolymerElements/paper-toggle-button#48]
When the element is disabled the color of the button and bar remains (the bar opacity is reduced). The demo shows this.

If I switch the CSS from using the class identifier to the id it behaves correctly. Not sure why that would be.

As is, does not work:

```
  :host([disabled]) .toggle-button {
    background-color: #bdbdbd;
    opacity: 1;
  }
```

works

```
  :host([disabled]) #toggleButton {
    background-color: #bdbdbd;
    opacity: 1;
  }
```

**Comment by notwaldorf** [comment]
Argh, sorry about this. It was recently introduced with a refactor. I'll get on it :)
