### ISSUE TITLE
v0.8.0 broken

### ISSUE THREAD

**Issue by michaelpg** [PolymerElements/paper-toggle-button#7]
Please release a new tag for 549a454111f00670853461fb2e6ac3d1194083f2 or 4b95f5177ddf44cbbd957371d29b10024e60c78e (I don't understand how these are separate commits, but whatever) so we have a working paper-toggle-button for Polymer v0.8.0-rc7.

:-)

**Comment by notwaldorf** [comment]
This is an old issue, and a new tag was already released, so closing this.
