### ISSUE TITLE
Rename paper-toggle-button to paper-switch?

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-toggle-button#71]
If the oficial Material Design name is "[Switch](https://www.google.com/design/spec/components/selection-controls.html#selection-controls-switch)", why the element is `paper-toggle-button` and not `paper-switch`? Also, `paper-switch` is shorter. :smiley:

**Comment by cdata** [comment]
TIL something new :) we probably won't do the rename right away, but this is a good insight. Thanks!

**Comment by abdonrd** [comment]
@cdata yeah, I imagine the retrocompatibility problems. Your welcome!

**Comment by bicknellr** [comment]
+1

**Comment by Talljoe** [comment]
Further more, "[Toggle Buttons](https://www.google.com/design/spec/components/buttons.html#buttons-toggle-buttons)" are something else entirely.

**Comment by abdonrd** [comment]
@cdata @notwaldorf friendly reminder for `Polymer v2.0`. :)

**Comment by stramel** [comment]
Just recently read this article http://inclusive-components.club/toggle-button/

It might be good to update some stuff, like `role`, `aria-checked`, initial `disabled`, and `aria-label`

**Comment by abdonrd** [comment]
As far as I know, the Polymer Elements are not going to continue developing. So I close this issue.
