### ISSUE TITLE
paper-toggle-button shouldn't disable vertical touch scrolling

### ISSUE THREAD

**Issue by keanulee** [PolymerElements/paper-toggle-button#91]
Should be fixed by `this.setScrollDirection('y')`

Orignal Issue (Polymer/paper-toggle-button#17) from @RByers:

In [demo page](https://elements.polymer-project.org/elements/paper-toggle-button?view=demo:demo/index.html&active=paper-toggle-button), touch on a toggle button and drag vertically.  The page should scroll, but instead the toggle drags.

/cc @esprehn

**Comment by bicknellr** [comment]
I'm not sure I buy that this bug is valid. It seems strange to be able to scroll the page and drag a switch at the same time.

**Comment by RByers** [comment]
No, it should always be one or the other.  I.e. if you start dragging horizontally it should toggle the switch and never scroll.  If you start dragging vertically it should scroll and never toggle the switch.

**Comment by bicknellr** [comment]
Ok, that sounds reasonable.
