### ISSUE TITLE
The `paper-toggle-button` is drawn in its own content

### ISSUE THREAD

**Issue by idanen** [PolymerElements/paper-toggle-button#92]
### Description

When creating a `paper-toggle-button` and cloning it (using vanilla JS) the button is drawn again inside its label
### Expected outcome

Should only draw elements children in the content placeholder
### Actual outcome

We see the button twice
### Live Demo

http://plnkr.co/edit/sDPxgi
### Steps to reproduce

1. Create a `paper-toggle-button` using `document.createElement()`
2. Clone it (`button.cloneNode()`)
3. Append it to an element (even `body`)
4. Watch the outcome
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
You need to use a `Polymer.dom()` [api method](https://www.polymer-project.org/1.0/docs/devguide/local-dom#dom-api) for this to work correctly, so that the DOM is properly cloned: http://jsbin.com/vazapi/edit?html,output

**Comment by idanen** [comment]
Cool. 
However, I originally stumbled upon this issue when using the element in an AngularJS app. The cloning is done by the framework so I'll need to hack it so it'll use Polymer and I'm trying to avoid it. 
Can you please provide a short explanation describing why does it happen so maybe I (or some other talented developer) can work on some kind of a solution? 
Thanks

**Comment by notwaldorf** [comment]
I've linked to the documentation page, which explains why this is needed. Here it is again, if you missed it: https://www.polymer-project.org/1.0/docs/devguide/local-dom (this section in particular: https://www.polymer-project.org/1.0/docs/devguide/local-dom#dom-api)

Basically, because you're using the shady DOM, you need a special API to modify the DOM.

**Comment by idanen** [comment]
So basically you're saying that it is not possible (at the moment?) to use this element with other frameworks (no interoperability, can't "use the platform")? 

To solve it for my small project I simply added a `select` to the `content` tag, but it didn't actually select the content I was giving... 

I'll gladly try other fixes unless you're saying it's not currently possible...

**Comment by idanen** [comment]
OK, apparently there's a flag to choose shadow DOM over shady DOM. So if anyone has the same issue, and you only need to support browsers that support shadow DOM, you can use this flag by adding

```
<script>window.Polymer = { dom: 'shadow' };</script>
```

to the document's `head` tag (before Polymer).
[previous example fixed in jsbin](http://jsbin.com/cucehuloyi/edit?html,output)
