### ISSUE TITLE
Allow the label to be positioned on the left side

### ISSUE THREAD

**Issue by viftodi** [PolymerElements/paper-toggle-button#94]
Currently the label is positioned on the right side and there is no direct way to position it on the left side.

It is useful in certain circumstances to position the label on the left side.

This component should allow such customization.

**Comment by bicknellr** [comment]
(Same situation as PolymerElements/paper-checkbox#125 : http://jsbin.com/kuqihu/1/edit?html,output .)

**Comment by hemantjadon** [comment]
can we wrap the `toggle-container` and `toggle-label` div in a `toggle-container-label-group` and use `display:flex`, `flex-direction:row` for right label, and `flex-direction:row-reverse` for left label

Reference to #95

**Comment by bicknellr** [comment]
Closing, see PolymerElements/paper-checkbox#125 for context.
